define([ 'ember-data' ], function (DS) {

	var cultivation = DS.Model.extend({
		title: DS.attr('string'),
		author: DS.attr('string'),
		authorTwitter: DS.attr('string'),
		intro: DS.attr('string'),
		full: DS.attr('string'),
		datePublished: DS.attr('date')
	});

	cultivation.FIXTURES = [
		{
			id: 1,
			title: 'My Little Pony',
			author: 'Cameron Puckett',
			authorTwitter: 'campuck',
			intro: 'One time Cameron had a little tiny pony.',
			full: 'Lorem ipsum Excepteur in cillum laboris consectetur in id officia deserunt aliquip est sed voluptate voluptate pariatur ad non id veniam esse irure ut sit tempor incididunt et aliqua veniam ea occaecat in minim esse aliquip commodo ea culpa Ut minim Excepteur elit dolore aliquip dolor ea ad qui pariatur id do sed minim mollit exercitation irure esse enim aute ad et id fugiat Duis consectetur aliqua in irure sunt laboris Excepteur velit et anim enim aute qui ut aliqua aliqua elit voluptate sunt non veniam Duis ut tempor proident ut Duis culpa magna veniam Ut ut aliqua consequat velit ad Ut culpa in dolor Ut est do sint id adipisicing voluptate quis dolore exercitation amet ut sunt anim ut non minim incididunt enim sed ad eiusmod occaecat fugiat adipisicing proident deserunt aliqua commodo esse do velit sit et est ut officia sunt est aute cupidatat commodo tempor elit labore sint amet enim eu tempor do esse nisi sint pariatur pariatur voluptate adipisicing tempor eu voluptate in in sit occaecat Duis nulla dolore qui in id esse fugiat tempor irure quis elit nisi Duis sunt eu nostrud magna pariatur minim ea magna laborum irure et cillum occaecat nisi est et consectetur in reprehenderit exercitation minim mollit Ut qui reprehenderit nulla consectetur et ut voluptate ad dolor in mollit qui fugiat et quis eiusmod in mollit ad sint aute ut sunt ut Duis anim nisi quis ea id tempor est eu culpa aute ea amet incididunt. Lorem ipsum Veniam fugiat non aliqua laboris eiusmod occaecat sunt Duis qui consequat cupidatat fugiat commodo minim aliquip adipisicing nostrud ullamco Excepteur reprehenderit Ut laboris anim labore cillum consequat quis laborum adipisicing dolore consequat cupidatat elit anim id amet Excepteur sit ut officia sed veniam elit laborum tempor in qui eu tempor sunt proident sed in elit dolore irure sit nostrud est do sed reprehenderit eu laboris culpa cillum proident occaecat ea occaecat ad eiusmod aliqua dolore Duis et fugiat irure et deserunt esse aliquip magna Ut anim proident enim laboris culpa enim sit id minim sit deserunt quis nostrud anim irure proident Ut ex reprehenderit anim Ut nisi enim consequat magna nostrud velit nulla occaecat nostrud deserunt laboris dolore qui ex officia sit labore in dolor culpa nulla commodo elit commodo nulla irure anim laboris eu reprehenderit voluptate culpa sunt adipisicing amet magna minim culpa.',
			datePublished: new Date('02-02-2013')
		},
		{
			id: 2,
			title: 'One Shiny Rock',
			author: 'Kevin Reed',
			authorTwitter: 'kavun',
			intro: 'One shiny rock.',
			full: 'Lorem ipsum Id fugiat sit est amet adipisicing tempor sed eu id exercitation elit do non consequat ex ut labore minim anim laborum Ut ex veniam sed incididunt in enim proident pariatur Excepteur qui laborum tempor aute Duis dolor proident nulla laborum est dolore sint do sed mollit Excepteur sit consequat aute ut quis esse ullamco in sit dolore et irure veniam est sit consectetur laboris dolore officia veniam fugiat minim do do sunt aliquip dolor Excepteur amet esse commodo irure dolore officia elit velit do amet aliqua reprehenderit laboris exercitation esse labore elit minim dolore cupidatat quis in velit cupidatat anim voluptate nulla Duis tempor labore do dolore sint anim non est nostrud pariatur ex officia adipisicing Excepteur nisi dolor fugiat est magna sit aute tempor sed ullamco ut eiusmod Duis proident sint adipisicing laborum aliquip veniam laborum commodo cupidatat commodo occaecat laborum ad Excepteur fugiat nisi deserunt fugiat amet laborum Excepteur reprehenderit sint est enim Duis cupidatat veniam Excepteur proident laborum culpa tempor in minim non tempor consequat consequat ad adipisicing Ut est aliqua aliquip qui ut elit cupidatat ut officia exercitation minim amet ad consectetur eu cillum do aliquip ex exercitation occaecat nulla quis aliqua eu incididunt aute ad et consectetur cillum Excepteur aute pariatur proident proident esse et do veniam in irure eu nostrud voluptate sed exercitation sit minim reprehenderit ut laborum consequat dolore dolor cupidatat cillum tempor sunt laborum veniam sint id exercitation aliqua minim elit reprehenderit magna enim officia sint irure dolor Excepteur eu eiusmod eiusmod ea nostrud labore anim commodo in in exercitation minim labore aliquip. Lorem ipsum Enim elit est fugiat sint in sint nisi quis proident officia dolor laboris ea est ea consectetur voluptate pariatur nostrud nulla consequat tempor id nisi ut Ut officia proident mollit mollit voluptate et officia ad do fugiat ut laborum aliqua quis eiusmod nostrud quis tempor magna deserunt ea veniam amet magna consequat incididunt culpa ea occaecat irure proident ut laborum aliqua incididunt dolore veniam id officia minim culpa dolor id aliqua laboris Duis non sunt ut esse tempor magna commodo nisi ad Ut elit cillum ut anim officia cupidatat fugiat reprehenderit ut pariatur eu Excepteur ex dolor sed labore ut do cillum in est fugiat minim consectetur aliqua dolore nostrud occaecat ut qui mollit minim consequat aliqua et do fugiat do laborum sint consequat adipisicing sit proident aute anim irure non do dolore aute pariatur consequat laboris reprehenderit do Ut sunt elit magna aliquip consequat adipisicing.',
			datePublished: new Date('01-01-2013')
		},
		{
			id: 3,
			title: 'Lorem ipsum Nostrud proident eu consequat.',
			author: 'Cameron Puckett',
			authorTwitter: 'campuck',
			intro: 'Lorem ipsum Ut et dolor elit irure ea.',
			full: 'Lorem ipsum Excepteur in cillum laboris consectetur in id officia deserunt aliquip est sed voluptate voluptate pariatur ad non id veniam esse irure ut sit tempor incididunt et aliqua veniam ea occaecat in minim esse aliquip commodo ea culpa Ut minim Excepteur elit dolore aliquip dolor ea ad qui pariatur id do sed minim mollit exercitation irure esse enim aute ad et id fugiat Duis consectetur aliqua in irure sunt laboris Excepteur velit et anim enim aute qui ut aliqua aliqua elit voluptate sunt non veniam Duis ut tempor proident ut Duis culpa magna veniam Ut ut aliqua consequat velit ad Ut culpa in dolor Ut est do sint id adipisicing voluptate quis dolore exercitation amet ut sunt anim ut non minim incididunt enim sed ad eiusmod occaecat fugiat adipisicing proident deserunt aliqua commodo esse do velit sit et est ut officia sunt est aute cupidatat commodo tempor elit labore sint amet enim eu tempor do esse nisi sint pariatur pariatur voluptate adipisicing tempor eu voluptate in in sit occaecat Duis nulla dolore qui in id esse fugiat tempor irure quis elit nisi Duis sunt eu nostrud magna pariatur minim ea magna laborum irure et cillum occaecat nisi est et consectetur in reprehenderit exercitation minim mollit Ut qui reprehenderit nulla consectetur et ut voluptate ad dolor in mollit qui fugiat et quis eiusmod in mollit ad sint aute ut sunt ut Duis anim nisi quis ea id tempor est eu culpa aute ea amet incididunt. Lorem ipsum Veniam fugiat non aliqua laboris eiusmod occaecat sunt Duis qui consequat cupidatat fugiat commodo minim aliquip adipisicing nostrud ullamco Excepteur reprehenderit Ut laboris anim labore cillum consequat quis laborum adipisicing dolore consequat cupidatat elit anim id amet Excepteur sit ut officia sed veniam elit laborum tempor in qui eu tempor sunt proident sed in elit dolore irure sit nostrud est do sed reprehenderit eu laboris culpa cillum proident occaecat ea occaecat ad eiusmod aliqua dolore Duis et fugiat irure et deserunt esse aliquip magna Ut anim proident enim laboris culpa enim sit id minim sit deserunt quis nostrud anim irure proident Ut ex reprehenderit anim Ut nisi enim consequat magna nostrud velit nulla occaecat nostrud deserunt laboris dolore qui ex officia sit labore in dolor culpa nulla commodo elit commodo nulla irure anim laboris eu reprehenderit voluptate culpa sunt adipisicing amet magna minim culpa.',
			datePublished: new Date('02-02-2013')
		},
		{
			id: 4,
			title: 'Lorem ipsum Sit officia sit labore in Duis.',
			author: 'Kevin Reed',
			authorTwitter: 'kavun',
			intro: 'Lorem ipsum Eiusmod enim commodo qui deserunt.',
			full: 'Lorem ipsum Id fugiat sit est amet adipisicing tempor sed eu id exercitation elit do non consequat ex ut labore minim anim laborum Ut ex veniam sed incididunt in enim proident pariatur Excepteur qui laborum tempor aute Duis dolor proident nulla laborum est dolore sint do sed mollit Excepteur sit consequat aute ut quis esse ullamco in sit dolore et irure veniam est sit consectetur laboris dolore officia veniam fugiat minim do do sunt aliquip dolor Excepteur amet esse commodo irure dolore officia elit velit do amet aliqua reprehenderit laboris exercitation esse labore elit minim dolore cupidatat quis in velit cupidatat anim voluptate nulla Duis tempor labore do dolore sint anim non est nostrud pariatur ex officia adipisicing Excepteur nisi dolor fugiat est magna sit aute tempor sed ullamco ut eiusmod Duis proident sint adipisicing laborum aliquip veniam laborum commodo cupidatat commodo occaecat laborum ad Excepteur fugiat nisi deserunt fugiat amet laborum Excepteur reprehenderit sint est enim Duis cupidatat veniam Excepteur proident laborum culpa tempor in minim non tempor consequat consequat ad adipisicing Ut est aliqua aliquip qui ut elit cupidatat ut officia exercitation minim amet ad consectetur eu cillum do aliquip ex exercitation occaecat nulla quis aliqua eu incididunt aute ad et consectetur cillum Excepteur aute pariatur proident proident esse et do veniam in irure eu nostrud voluptate sed exercitation sit minim reprehenderit ut laborum consequat dolore dolor cupidatat cillum tempor sunt laborum veniam sint id exercitation aliqua minim elit reprehenderit magna enim officia sint irure dolor Excepteur eu eiusmod eiusmod ea nostrud labore anim commodo in in exercitation minim labore aliquip. Lorem ipsum Enim elit est fugiat sint in sint nisi quis proident officia dolor laboris ea est ea consectetur voluptate pariatur nostrud nulla consequat tempor id nisi ut Ut officia proident mollit mollit voluptate et officia ad do fugiat ut laborum aliqua quis eiusmod nostrud quis tempor magna deserunt ea veniam amet magna consequat incididunt culpa ea occaecat irure proident ut laborum aliqua incididunt dolore veniam id officia minim culpa dolor id aliqua laboris Duis non sunt ut esse tempor magna commodo nisi ad Ut elit cillum ut anim officia cupidatat fugiat reprehenderit ut pariatur eu Excepteur ex dolor sed labore ut do cillum in est fugiat minim consectetur aliqua dolore nostrud occaecat ut qui mollit minim consequat aliqua et do fugiat do laborum sint consequat adipisicing sit proident aute anim irure non do dolore aute pariatur consequat laboris reprehenderit do Ut sunt elit magna aliquip consequat adipisicing.',
			datePublished: new Date('01-01-2013')
		},
		{
			id: 5,
			title: 'Lorem ipsum Occaecat ea veniam Duis eiusmod.',
			author: 'Cameron Puckett',
			authorTwitter: 'campuck',
			intro: 'Lorem ipsum Reprehenderit tempor do deserunt nulla aliquip.',
			full: 'Lorem ipsum Excepteur in cillum laboris consectetur in id officia deserunt aliquip est sed voluptate voluptate pariatur ad non id veniam esse irure ut sit tempor incididunt et aliqua veniam ea occaecat in minim esse aliquip commodo ea culpa Ut minim Excepteur elit dolore aliquip dolor ea ad qui pariatur id do sed minim mollit exercitation irure esse enim aute ad et id fugiat Duis consectetur aliqua in irure sunt laboris Excepteur velit et anim enim aute qui ut aliqua aliqua elit voluptate sunt non veniam Duis ut tempor proident ut Duis culpa magna veniam Ut ut aliqua consequat velit ad Ut culpa in dolor Ut est do sint id adipisicing voluptate quis dolore exercitation amet ut sunt anim ut non minim incididunt enim sed ad eiusmod occaecat fugiat adipisicing proident deserunt aliqua commodo esse do velit sit et est ut officia sunt est aute cupidatat commodo tempor elit labore sint amet enim eu tempor do esse nisi sint pariatur pariatur voluptate adipisicing tempor eu voluptate in in sit occaecat Duis nulla dolore qui in id esse fugiat tempor irure quis elit nisi Duis sunt eu nostrud magna pariatur minim ea magna laborum irure et cillum occaecat nisi est et consectetur in reprehenderit exercitation minim mollit Ut qui reprehenderit nulla consectetur et ut voluptate ad dolor in mollit qui fugiat et quis eiusmod in mollit ad sint aute ut sunt ut Duis anim nisi quis ea id tempor est eu culpa aute ea amet incididunt. Lorem ipsum Veniam fugiat non aliqua laboris eiusmod occaecat sunt Duis qui consequat cupidatat fugiat commodo minim aliquip adipisicing nostrud ullamco Excepteur reprehenderit Ut laboris anim labore cillum consequat quis laborum adipisicing dolore consequat cupidatat elit anim id amet Excepteur sit ut officia sed veniam elit laborum tempor in qui eu tempor sunt proident sed in elit dolore irure sit nostrud est do sed reprehenderit eu laboris culpa cillum proident occaecat ea occaecat ad eiusmod aliqua dolore Duis et fugiat irure et deserunt esse aliquip magna Ut anim proident enim laboris culpa enim sit id minim sit deserunt quis nostrud anim irure proident Ut ex reprehenderit anim Ut nisi enim consequat magna nostrud velit nulla occaecat nostrud deserunt laboris dolore qui ex officia sit labore in dolor culpa nulla commodo elit commodo nulla irure anim laboris eu reprehenderit voluptate culpa sunt adipisicing amet magna minim culpa.',
			datePublished: new Date('02-02-2013')
		},
		{
			id: 6,
			title: 'Lorem ipsum Magna incididunt sunt dolor cupidatat.',
			author: 'Kevin Reed',
			authorTwitter: 'kavun',
			intro: 'Lorem ipsum Nostrud elit esse dolor ut cillum.',
			full: 'Lorem ipsum Id fugiat sit est amet adipisicing tempor sed eu id exercitation elit do non consequat ex ut labore minim anim laborum Ut ex veniam sed incididunt in enim proident pariatur Excepteur qui laborum tempor aute Duis dolor proident nulla laborum est dolore sint do sed mollit Excepteur sit consequat aute ut quis esse ullamco in sit dolore et irure veniam est sit consectetur laboris dolore officia veniam fugiat minim do do sunt aliquip dolor Excepteur amet esse commodo irure dolore officia elit velit do amet aliqua reprehenderit laboris exercitation esse labore elit minim dolore cupidatat quis in velit cupidatat anim voluptate nulla Duis tempor labore do dolore sint anim non est nostrud pariatur ex officia adipisicing Excepteur nisi dolor fugiat est magna sit aute tempor sed ullamco ut eiusmod Duis proident sint adipisicing laborum aliquip veniam laborum commodo cupidatat commodo occaecat laborum ad Excepteur fugiat nisi deserunt fugiat amet laborum Excepteur reprehenderit sint est enim Duis cupidatat veniam Excepteur proident laborum culpa tempor in minim non tempor consequat consequat ad adipisicing Ut est aliqua aliquip qui ut elit cupidatat ut officia exercitation minim amet ad consectetur eu cillum do aliquip ex exercitation occaecat nulla quis aliqua eu incididunt aute ad et consectetur cillum Excepteur aute pariatur proident proident esse et do veniam in irure eu nostrud voluptate sed exercitation sit minim reprehenderit ut laborum consequat dolore dolor cupidatat cillum tempor sunt laborum veniam sint id exercitation aliqua minim elit reprehenderit magna enim officia sint irure dolor Excepteur eu eiusmod eiusmod ea nostrud labore anim commodo in in exercitation minim labore aliquip. Lorem ipsum Enim elit est fugiat sint in sint nisi quis proident officia dolor laboris ea est ea consectetur voluptate pariatur nostrud nulla consequat tempor id nisi ut Ut officia proident mollit mollit voluptate et officia ad do fugiat ut laborum aliqua quis eiusmod nostrud quis tempor magna deserunt ea veniam amet magna consequat incididunt culpa ea occaecat irure proident ut laborum aliqua incididunt dolore veniam id officia minim culpa dolor id aliqua laboris Duis non sunt ut esse tempor magna commodo nisi ad Ut elit cillum ut anim officia cupidatat fugiat reprehenderit ut pariatur eu Excepteur ex dolor sed labore ut do cillum in est fugiat minim consectetur aliqua dolore nostrud occaecat ut qui mollit minim consequat aliqua et do fugiat do laborum sint consequat adipisicing sit proident aute anim irure non do dolore aute pariatur consequat laboris reprehenderit do Ut sunt elit magna aliquip consequat adipisicing.',
			datePublished: new Date('01-01-2013')
		},
		{
			id: 7,
			title: 'Lorem ipsum Mollit sint laborum aliqua.',
			author: 'Cameron Puckett',
			authorTwitter: 'campuck',
			intro: 'Lorem ipsum Cillum culpa laboris ut.',
			full: 'Lorem ipsum Excepteur in cillum laboris consectetur in id officia deserunt aliquip est sed voluptate voluptate pariatur ad non id veniam esse irure ut sit tempor incididunt et aliqua veniam ea occaecat in minim esse aliquip commodo ea culpa Ut minim Excepteur elit dolore aliquip dolor ea ad qui pariatur id do sed minim mollit exercitation irure esse enim aute ad et id fugiat Duis consectetur aliqua in irure sunt laboris Excepteur velit et anim enim aute qui ut aliqua aliqua elit voluptate sunt non veniam Duis ut tempor proident ut Duis culpa magna veniam Ut ut aliqua consequat velit ad Ut culpa in dolor Ut est do sint id adipisicing voluptate quis dolore exercitation amet ut sunt anim ut non minim incididunt enim sed ad eiusmod occaecat fugiat adipisicing proident deserunt aliqua commodo esse do velit sit et est ut officia sunt est aute cupidatat commodo tempor elit labore sint amet enim eu tempor do esse nisi sint pariatur pariatur voluptate adipisicing tempor eu voluptate in in sit occaecat Duis nulla dolore qui in id esse fugiat tempor irure quis elit nisi Duis sunt eu nostrud magna pariatur minim ea magna laborum irure et cillum occaecat nisi est et consectetur in reprehenderit exercitation minim mollit Ut qui reprehenderit nulla consectetur et ut voluptate ad dolor in mollit qui fugiat et quis eiusmod in mollit ad sint aute ut sunt ut Duis anim nisi quis ea id tempor est eu culpa aute ea amet incididunt. Lorem ipsum Veniam fugiat non aliqua laboris eiusmod occaecat sunt Duis qui consequat cupidatat fugiat commodo minim aliquip adipisicing nostrud ullamco Excepteur reprehenderit Ut laboris anim labore cillum consequat quis laborum adipisicing dolore consequat cupidatat elit anim id amet Excepteur sit ut officia sed veniam elit laborum tempor in qui eu tempor sunt proident sed in elit dolore irure sit nostrud est do sed reprehenderit eu laboris culpa cillum proident occaecat ea occaecat ad eiusmod aliqua dolore Duis et fugiat irure et deserunt esse aliquip magna Ut anim proident enim laboris culpa enim sit id minim sit deserunt quis nostrud anim irure proident Ut ex reprehenderit anim Ut nisi enim consequat magna nostrud velit nulla occaecat nostrud deserunt laboris dolore qui ex officia sit labore in dolor culpa nulla commodo elit commodo nulla irure anim laboris eu reprehenderit voluptate culpa sunt adipisicing amet magna minim culpa.',
			datePublished: new Date('02-02-2013')
		},
		{
			id: 8,
			title: 'Lorem ipsum Ut consequat elit aliquip.',
			author: 'Kevin Reed',
			authorTwitter: 'kavun',
			intro: 'Lorem ipsum Non ad in dolor deserunt.',
			full: 'Lorem ipsum Id fugiat sit est amet adipisicing tempor sed eu id exercitation elit do non consequat ex ut labore minim anim laborum Ut ex veniam sed incididunt in enim proident pariatur Excepteur qui laborum tempor aute Duis dolor proident nulla laborum est dolore sint do sed mollit Excepteur sit consequat aute ut quis esse ullamco in sit dolore et irure veniam est sit consectetur laboris dolore officia veniam fugiat minim do do sunt aliquip dolor Excepteur amet esse commodo irure dolore officia elit velit do amet aliqua reprehenderit laboris exercitation esse labore elit minim dolore cupidatat quis in velit cupidatat anim voluptate nulla Duis tempor labore do dolore sint anim non est nostrud pariatur ex officia adipisicing Excepteur nisi dolor fugiat est magna sit aute tempor sed ullamco ut eiusmod Duis proident sint adipisicing laborum aliquip veniam laborum commodo cupidatat commodo occaecat laborum ad Excepteur fugiat nisi deserunt fugiat amet laborum Excepteur reprehenderit sint est enim Duis cupidatat veniam Excepteur proident laborum culpa tempor in minim non tempor consequat consequat ad adipisicing Ut est aliqua aliquip qui ut elit cupidatat ut officia exercitation minim amet ad consectetur eu cillum do aliquip ex exercitation occaecat nulla quis aliqua eu incididunt aute ad et consectetur cillum Excepteur aute pariatur proident proident esse et do veniam in irure eu nostrud voluptate sed exercitation sit minim reprehenderit ut laborum consequat dolore dolor cupidatat cillum tempor sunt laborum veniam sint id exercitation aliqua minim elit reprehenderit magna enim officia sint irure dolor Excepteur eu eiusmod eiusmod ea nostrud labore anim commodo in in exercitation minim labore aliquip. Lorem ipsum Enim elit est fugiat sint in sint nisi quis proident officia dolor laboris ea est ea consectetur voluptate pariatur nostrud nulla consequat tempor id nisi ut Ut officia proident mollit mollit voluptate et officia ad do fugiat ut laborum aliqua quis eiusmod nostrud quis tempor magna deserunt ea veniam amet magna consequat incididunt culpa ea occaecat irure proident ut laborum aliqua incididunt dolore veniam id officia minim culpa dolor id aliqua laboris Duis non sunt ut esse tempor magna commodo nisi ad Ut elit cillum ut anim officia cupidatat fugiat reprehenderit ut pariatur eu Excepteur ex dolor sed labore ut do cillum in est fugiat minim consectetur aliqua dolore nostrud occaecat ut qui mollit minim consequat aliqua et do fugiat do laborum sint consequat adipisicing sit proident aute anim irure non do dolore aute pariatur consequat laboris reprehenderit do Ut sunt elit magna aliquip consequat adipisicing.',
			datePublished: new Date('01-01-2013')
		}
	];

	return cultivation;
});